### ISSUE TITLE
pull code from terraform don't create tf files in common-jenkins repo

### ISSUE THREAD

**Issue by fsadykov** [fuchicorp/common-jenkins#12]
Hello,

Please use this feature on your groovy file to poll the tf files. Do not create tf files in common-jenkins. 

```
node {
  stage('Checkout SCM') {
   git 'https://github.com/fuchicorp/terraform.git'
  }

  stage('terraform Apply') {
    dir("${WORKSPACE}/google_nexus/") {
      sh "terraform apply"
    }
  }
}
```

**Comment by fsadykov** [comment]
Roman Would you please re-create the PR

**Comment by fsadykov** [comment]
Please delete a part which will use the roman branch

**Comment by Murodbey** [comment]
I think  @karakyrt  took this ticket and he already finished it!
