### ISSUE TITLE
Integrations with Slack

### ISSUE THREAD

**Issue by SharifAbdulcoder** [fuchicorp/common-jenkins#20]
Please integrate your Jenkins job with Slack. Every time you run your job it should notify us all in our slack system.
Please include nice readme file
Create a PL just for this specific ticket
Thank you

**Comment by NadiraSaip** [comment]
I have integrated "grafana_deploymentNadira" job with Slack. If any adjustments made in jenkinsfile.groovy Slack will automatically inform and update you with the change. All updates are posted under channel #test-message. 
There is no need to create a pull request as my code was successfully deployed.  
I am still working on readme file.

**Comment by fsadykov** [comment]
Please create PR for this feature
