### ISSUE TITLE
Jira Jenkins Job

### ISSUE THREAD

**Issue by SharifAbdulcoder** [fuchicorp/common-jenkins#8]
Please write a jenkinsfile for Jira and deploy it using Terraform. Make sure Jira is up and running in TOOLS namespace. Don't forget to create PR, and include nice README file.

ESTIMATED: 1

**Comment by fsadykov** [comment]
Please re-create your PR. I don't know why you delete the grafana deployment files

**Comment by fsadykov** [comment]
Still working on

**Comment by fsadykov** [comment]
Merged and closed
